workflow: allowed exit 124 to not be failure and kernel log dump on fail added

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -37,5 +37,17 @@ jobs:
           # Run it in the background
           python3 sim_ransom.py &
           echo "SIM_PID=$!" >> $GITHUB_ENV
-          sudo timeout 5s ./sentinel
+          sudo timeout 20s ./sentinel > output.log|| [ $? -eq 124 ] || [ $? -eq 124 ]
           kill $SIM_PID
+        if grep -p "BLOCK:" output.log; then
+          echo "Pass! logs:\n"
+          cat output.log
+        else
+          echo "Fail! logs:\n"
+          cat output.log
+          exit 1
+        fi
+
+      - name: Check dmesg on fail
+        if: failure()
+        run: sudo dmesg | tail -n 50
